[project]
name = "ac-downloader"
version = "0.1.0"
description = "Adobe Connect downloader"
dependencies = ["core", "cli"]


[tool.uv.workspace]
members = [
    'packages/base',
    'packages/cli'
]

[tool.uv.sources]
core = { workspace = true }
cli = { workspace = true }

[tool.ruff]

line-length = 88
indent-width = 4

extend-exclude = [".idea", "docs", "output", "storage"]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["S101", "ANN", "ANN001", "ANN201"]


[tool.ruff.lint]

select = [
    "E",
    "W",
    "I",
    "UP",
    "B",
    "SIM",
    "C4",
    "N",
    "ANN",
    "ASYNC",
    "A",
    "DTZ",
    "PT",
    "RET",
    "RUF",
    "S",
    "PERF",
    "PTH",
]


[tool.ruff.format]

line-ending = "auto"
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = "dynamic"
skip-magic-trailing-comma = false

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.11.0",
]

[tool.pytest.ini_options]
pythonpath = ["packages/cli/src", "packages/base/src"]
testpaths = ["packages"]
